name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.6.1'

      - name: Get changed pyproject files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v lavague-core | grep lavague | grep pyproject | xargs)" >> $GITHUB_OUTPUT

      - name: Publish changed packages
        env:
          PYPI_TOKEN: ${{ secrets.LAVAGUE_PYPI_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
              cd `echo $file | sed 's/\/pyproject.toml//g'`
              poetry lock
              pip install -e .
              poetry config pypi-token.pypi $PYPI_TOKEN
              poetry publish --build
              cd -
          done